"use client";

import { ChangeEvent, FormEvent, useState } from "react";
import { FiArchive, FiCheck, FiCopy, FiEdit2, FiLoader, FiTrash2, FiUpload, FiX } from "react-icons/fi";
import type { AdminAttribute, AdminTaxonomyTerm, AdminTrim, AdminTrimPayload, JsonObject, JsonValue } from "@autosecure/api";
import { adminApi, getAdminErrorMessage } from "@/lib/admin-api";
import { notifyError, notifySuccess } from "@/lib/admin-notifications";

export type ConfirmAction = "publish" | "unpublish" | "archive" | "delete" | null;

export function TrimWorkspace({ mode, trim, taxonomy, attributes, accessToken, actionKey, onClose, onEdit, onSaved, onConfirm, onVerify, onDuplicate, onUpload }: { mode: "view" | "edit" | "create"; trim: AdminTrim | null; taxonomy: AdminTaxonomyTerm[]; attributes: AdminAttribute[]; accessToken: string | null; actionKey: string | null; onClose: () => void; onEdit: () => void; onSaved: (trim: AdminTrim) => Promise<void>; onConfirm: (action: ConfirmAction) => void; onVerify: () => void; onDuplicate: () => void; onUpload: (event: ChangeEvent<HTMLInputElement>) => void }) {
  return <div className="fixed inset-0 z-50"><button type="button" aria-label="Close trim workspace" className="absolute inset-0 bg-slate-950/55" onClick={onClose} /><aside role="dialog" aria-modal="true" aria-labelledby="trim-workspace-title" className="absolute inset-y-0 right-0 w-full max-w-4xl overflow-y-auto bg-white shadow-2xl">
    <div className="sticky top-0 z-10 flex items-center justify-between border-b border-[var(--admin-line)] bg-white px-6 py-5"><div><h2 id="trim-workspace-title" className="font-display text-xl font-bold">{mode === "create" ? "Add vehicle trim" : mode === "edit" ? "Edit vehicle trim" : trim?.name}</h2>{trim ? <p className="mt-1 text-xs text-[var(--admin-muted)]">{trim.slug} · {trim.status ?? "DRAFT"}</p> : null}</div><button type="button" onClick={onClose} aria-label="Close" className="rounded-lg p-2 hover:bg-slate-100"><FiX /></button></div>
    {mode !== "view" ? <TrimForm item={mode === "edit" ? trim : null} taxonomy={taxonomy} attributes={attributes} accessToken={accessToken} onCancel={mode === "create" ? onClose : () => void onSaved(trim!)} onSaved={onSaved} /> : trim ? <div className="space-y-6 p-6">
      <div className="flex flex-wrap gap-2"><Action icon={FiEdit2} label="Edit" onClick={onEdit} /><Action icon={FiCheck} label="Verify sections" onClick={onVerify} disabled={!trim.unverifiedSections?.length} /><Action icon={FiCopy} label="Duplicate" onClick={onDuplicate} /><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-[var(--admin-line)] px-3 py-2 text-xs font-bold"><FiUpload />{actionKey === "images" ? "Uploading…" : "Upload images"}<input type="file" accept="image/*" multiple disabled={actionKey === "images"} onChange={onUpload} className="sr-only" /></label>{trim.status === "PUBLISHED" ? <Action icon={FiArchive} label="Return to draft" onClick={() => onConfirm("unpublish")} /> : <Action icon={FiCheck} label="Publish" onClick={() => onConfirm("publish")} disabled={Boolean(trim.unverifiedSections?.length) || trim.status === "ARCHIVED"} />}{trim.status !== "ARCHIVED" ? <Action icon={FiArchive} label="Archive" onClick={() => onConfirm("archive")} /> : null}<Action icon={FiTrash2} label="Delete" onClick={() => onConfirm("delete")} disabled={Boolean(trim.listingCount)} danger /></div>
      {trim.unverifiedSections?.length ? <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">Publishing is blocked until these sections are verified: {trim.unverifiedSections.join(", ")}.</div> : null}
      {trim.listingCount ? <p className="text-sm text-[var(--admin-muted)]">Referenced by {trim.listingCount} listing(s). Archive is available; deletion is disabled.</p> : null}
      <dl className="grid gap-x-8 gap-y-5 sm:grid-cols-2 lg:grid-cols-3"><Datum label="Brand" value={trim.brandName ?? trim.brandSlug} /><Datum label="Model" value={trim.modelName ?? trim.modelSlug} /><Datum label="Model year" value={`${trim.year}${trim.yearTo ? `–${trim.yearTo}` : ""}`} /><Datum label="Body type" value={trim.bodyType} /><Datum label="Powertrain" value={trim.powertrain} /><Datum label="Drive type" value={trim.driveType} /><Datum label="Country" value={trim.countryOfOrigin} /><Datum label="Images" value={String(trim.images?.length ?? 0)} /><Datum label="Listings" value={String(trim.listingCount ?? 0)} /></dl>
      <JsonSection title="Specifications" value={trim.specs} /><JsonSection title="Review" value={trim.review} /><JsonSection title="Provenance" value={trim.provenance} />
    </div> : null}
  </aside></div>;
}

function TrimForm({ item, taxonomy, attributes, accessToken, onCancel, onSaved }: { item: AdminTrim | null; taxonomy: AdminTaxonomyTerm[]; attributes: AdminAttribute[]; accessToken: string | null; onCancel: () => void; onSaved: (trim: AdminTrim) => Promise<void> }) {
  const [brandSlug, setBrandSlug] = useState(item?.brandSlug ?? "");
  const [modelSlug, setModelSlug] = useState(item?.modelSlug ?? "");
  const [name, setName] = useState(item?.name ?? "");
  const [year, setYear] = useState(String(item?.year ?? new Date().getFullYear()));
  const [yearTo, setYearTo] = useState(item?.yearTo ? String(item.yearTo) : "");
  const [vehicleCategories, setVehicleCategories] = useState(item?.vehicleCategories ?? []);
  const [vehicleType, setVehicleType] = useState(item?.vehicleType ?? "");
  const [bodyType, setBodyType] = useState(item?.bodyType ?? "");
  const [powertrain, setPowertrain] = useState(item?.powertrain ?? "");
  const [driveType, setDriveType] = useState(item?.driveType ?? "");
  const [useCases, setUseCases] = useState(item?.useCases ?? []);
  const [country, setCountry] = useState(item?.countryOfOrigin ?? "");
  const [colours, setColours] = useState(item?.availableColours?.join("\n") ?? "");
  const [specsText, setSpecsText] = useState(JSON.stringify(item?.specs ?? {}, null, 2));
  const [reviewText, setReviewText] = useState(JSON.stringify(item?.review ?? {}, null, 2));
  const [minPrice, setMinPrice] = useState(item?.priceRange?.min === undefined ? "" : String(item.priceRange.min));
  const [maxPrice, setMaxPrice] = useState(item?.priceRange?.max === undefined ? "" : String(item.priceRange.max));
  const [currency, setCurrency] = useState(item?.priceRange?.currency ?? "NGN");
  const [landingCostNote, setLandingCostNote] = useState(item?.landingCostNote ?? "");
  const [fieldError, setFieldError] = useState("");
  const [isSaving, setIsSaving] = useState(false);
  const kinds = (kind: string) => taxonomy.filter((term) => term.kind === kind);
  const brands = kinds("BRAND");
  const brandId = brands.find((term) => term.slug === brandSlug)?._id;
  const models = kinds("MODEL").filter((term) => !brandId || term.parent === brandId || term.slug === modelSlug);

  function updateDynamic(attribute: AdminAttribute, raw: string) { let specs: JsonObject; try { specs = JSON.parse(specsText) as JsonObject; } catch { return setFieldError("Fix the specifications JSON before changing dynamic fields."); } const path = attribute.path.replace(/^specs\./, "").split("."); const value: JsonValue = attribute.dataType === "NUMBER" ? (raw === "" ? null : Number(raw)) : attribute.dataType === "BOOLEAN" ? raw === "true" : raw; setNested(specs, path, value); setSpecsText(JSON.stringify(specs, null, 2)); }
  async function submit(event: FormEvent) {
    event.preventDefault(); setFieldError("");
    if (!brandSlug || !modelSlug || !name.trim()) return setFieldError("Brand, model, and trim name are required.");
    const parsedYear = Number(year); if (!Number.isInteger(parsedYear)) return setFieldError("Enter a valid model year.");
    let specs: JsonObject; let review: JsonObject;
    try { specs = JSON.parse(specsText) as JsonObject; review = JSON.parse(reviewText) as JsonObject; if (!specs || Array.isArray(specs) || !review || Array.isArray(review)) throw new Error(); }
    catch { return setFieldError("Specifications and review must both be valid JSON objects."); }
    const min = minPrice ? Number(minPrice) : undefined; const max = maxPrice ? Number(maxPrice) : undefined;
    if (min !== undefined && max !== undefined && min > max) return setFieldError("Minimum price cannot be greater than maximum price.");
    if (!accessToken) return;
    const payload: AdminTrimPayload = { brandSlug, modelSlug, name: name.trim(), year: parsedYear, yearTo: yearTo ? Number(yearTo) : undefined, vehicleCategories, vehicleType: vehicleType || undefined, bodyType: bodyType || undefined, powertrain: powertrain || undefined, driveType: driveType || undefined, useCases, countryOfOrigin: country.trim() || undefined, availableColours: splitList(colours), specs, review, priceRange: min !== undefined || max !== undefined ? { min, max, currency } : undefined, landingCostNote: landingCostNote.trim() || undefined, images: item?.images ?? [] };
    setIsSaving(true);
    try { const response = item ? await adminApi.updateTrim(accessToken, item._id, payload) : await adminApi.createTrim(accessToken, payload); notifySuccess(item ? "Trim updated." : "Trim created as a draft."); await onSaved(response.data); }
    catch (requestError) { notifyError(getAdminErrorMessage(requestError)); }
    finally { setIsSaving(false); }
  }

  return <form onSubmit={submit} className="space-y-8 p-6">
    <FormSection title="Identity"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><SelectField label="Brand" value={brandSlug} onChange={(value) => { setBrandSlug(value); setModelSlug(""); }} options={brands.map((term) => [term.slug, term.name])} /><SelectField label="Model" value={modelSlug} onChange={setModelSlug} options={models.map((term) => [term.slug, term.name])} /><TextField label="Trim name" value={name} onChange={setName} /><TextField label="Year" value={year} onChange={setYear} type="number" /><TextField label="Year to" value={yearTo} onChange={setYearTo} type="number" /><TextField label="Country of origin" value={country} onChange={setCountry} /></div></FormSection>
    <FormSection title="Classification"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><TaxonomySelect label="Vehicle type" kind="VEHICLE_TYPE" value={vehicleType} setValue={setVehicleType} taxonomy={taxonomy} /><TaxonomySelect label="Body type" kind="BODY_TYPE" value={bodyType} setValue={setBodyType} taxonomy={taxonomy} /><TaxonomySelect label="Powertrain" kind="POWERTRAIN" value={powertrain} setValue={setPowertrain} taxonomy={taxonomy} /><TaxonomySelect label="Drive type" kind="DRIVE_TYPE" value={driveType} setValue={setDriveType} taxonomy={taxonomy} /><MultiSelect label="Vehicle categories" options={kinds("VEHICLE_CATEGORY")} values={vehicleCategories} setValues={setVehicleCategories} /><MultiSelect label="Use cases" options={kinds("USE_CASE")} values={useCases} setValues={setUseCases} /></div></FormSection>
    <FormSection title="Dynamic specifications" description="These controls come from active vehicle attributes. Use the JSON editor for specifications not yet defined as attributes."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{attributes.map((attribute) => <DynamicField key={attribute._id} attribute={attribute} specsText={specsText} onChange={(value) => updateDynamic(attribute, value)} />)}</div><label className="mt-5 block text-sm font-semibold">Complete specifications JSON<textarea value={specsText} onChange={(event) => setSpecsText(event.target.value)} className="mt-2 min-h-64 w-full rounded-lg border border-[var(--admin-line)] p-3 font-mono text-sm" /></label></FormSection>
    <FormSection title="Review, pricing, and presentation"><label className="block text-sm font-semibold">Review JSON<textarea value={reviewText} onChange={(event) => setReviewText(event.target.value)} className="mt-2 min-h-40 w-full rounded-lg border border-[var(--admin-line)] p-3 font-mono text-sm" /></label><div className="mt-4 grid gap-4 sm:grid-cols-3"><TextField label="Minimum price" value={minPrice} onChange={setMinPrice} type="number" /><TextField label="Maximum price" value={maxPrice} onChange={setMaxPrice} type="number" /><TextField label="Currency" value={currency} onChange={setCurrency} /></div><label className="mt-4 block text-sm font-semibold">Available colours<textarea value={colours} onChange={(event) => setColours(event.target.value)} className="mt-2 min-h-24 w-full rounded-lg border border-[var(--admin-line)] p-3 text-sm" placeholder="One colour per line" /></label><label className="mt-4 block text-sm font-semibold">Landing cost note<textarea value={landingCostNote} onChange={(event) => setLandingCostNote(event.target.value)} className="mt-2 min-h-24 w-full rounded-lg border border-[var(--admin-line)] p-3 text-sm" /></label></FormSection>
    {fieldError ? <p role="alert" className="text-sm text-red-700">{fieldError}</p> : null}<div className="sticky bottom-0 flex justify-end gap-3 border-t bg-white py-4"><button type="button" onClick={onCancel} className="px-4 py-2 text-sm font-bold">Cancel</button><button type="submit" disabled={isSaving} className="inline-flex items-center gap-2 rounded-lg bg-[var(--admin-navy)] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{isSaving ? <FiLoader className="animate-spin" /> : null}{item ? "Save changes" : "Create trim"}</button></div>
  </form>;
}

export function VerifyDialog({ trim, accessToken, onClose, onSaved }: { trim: AdminTrim; accessToken: string | null; onClose: () => void; onSaved: (trim: AdminTrim) => Promise<void> }) { const pending = trim.unverifiedSections ?? []; const [selected, setSelected] = useState<string[]>(pending); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); if (!accessToken || !selected.length) return; setSaving(true); try { const response = await adminApi.verifyTrimSections(accessToken, trim._id, { sections: selected.length === pending.length ? "all" : selected, note: note.trim() || undefined }); await onSaved(response.data); } catch (error) { notifyError(getAdminErrorMessage(error)); } finally { setSaving(false); } } return <Modal title="Verify trim sections" onClose={onClose}><form onSubmit={submit} className="space-y-4">{pending.map((section) => <label key={section} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={selected.includes(section)} onChange={() => setSelected((current) => current.includes(section) ? current.filter((value) => value !== section) : [...current, section])} /> {formatLabel(section)}</label>)}<label className="block text-sm font-semibold">Verification note<textarea value={note} onChange={(event) => setNote(event.target.value)} className="mt-2 min-h-24 w-full rounded-lg border p-3" /></label><DialogButtons saving={saving} label="Verify selected" onCancel={onClose} disabled={!selected.length} /></form></Modal>; }
export function DuplicateDialog({ trim, accessToken, onClose, onSaved }: { trim: AdminTrim; accessToken: string | null; onClose: () => void; onSaved: () => Promise<void> }) { const [year, setYear] = useState(String(trim.year + 1)); const [name, setName] = useState(trim.name); const [saving, setSaving] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); if (!accessToken) return; setSaving(true); try { await adminApi.duplicateTrim(accessToken, trim._id, { year: Number(year), name: name.trim() || undefined }); notifySuccess("Trim duplicated as a draft."); await onSaved(); } catch (error) { notifyError(getAdminErrorMessage(error)); } finally { setSaving(false); } } return <Modal title="Duplicate trim" onClose={onClose}><form onSubmit={submit} className="space-y-4"><TextField label="New model year" value={year} onChange={setYear} type="number" /><TextField label="Trim name" value={name} onChange={setName} /><DialogButtons saving={saving} label="Create duplicate" onCancel={onClose} /></form></Modal>; }

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center p-5"><button type="button" className="absolute inset-0 bg-slate-950/55" aria-label="Close dialog" onClick={onClose} /><div role="dialog" aria-modal="true" className="relative w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="font-display text-xl font-bold">{title}</h2><button type="button" onClick={onClose}><FiX /></button></div>{children}</div></div>; }
function DialogButtons({ saving, label, onCancel, disabled = false }: { saving: boolean; label: string; onCancel: () => void; disabled?: boolean }) { return <div className="flex justify-end gap-3 border-t pt-4"><button type="button" onClick={onCancel} className="px-4 py-2 text-sm font-bold">Cancel</button><button type="submit" disabled={saving || disabled} className="inline-flex items-center gap-2 rounded-lg bg-[var(--admin-navy)] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? <FiLoader className="animate-spin" /> : null}{label}</button></div>; }
function Action({ icon: Icon, label, onClick, disabled = false, danger = false }: { icon: typeof FiEdit2; label: string; onClick: () => void; disabled?: boolean; danger?: boolean }) { return <button type="button" onClick={onClick} disabled={disabled} title={disabled ? "This action is not currently available" : label} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-40 ${danger ? "border-red-200 text-red-700" : "border-[var(--admin-line)]"}`}><Icon /> {label}</button>; }
function Datum({ label, value }: { label: string; value?: string }) { return <div><dt className="text-xs font-bold text-[var(--admin-muted)]">{label}</dt><dd className="mt-1 text-sm font-semibold">{value || "Not set"}</dd></div>; }
function JsonSection({ title, value }: { title: string; value?: JsonValue | JsonObject }) { return <details className="border-t pt-4"><summary className="cursor-pointer text-sm font-bold">{title}</summary><pre className="mt-3 overflow-x-auto rounded-lg bg-slate-50 p-4 text-xs">{JSON.stringify(value ?? {}, null, 2)}</pre></details>; }
function FormSection({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="border-b pb-7"><h3 className="font-display text-lg font-bold">{title}</h3>{description ? <p className="mt-1 mb-4 text-xs text-[var(--admin-muted)]">{description}</p> : <div className="h-4" />}{children}</section>; }
function TextField({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: "text" | "number" }) { return <label className="text-sm font-semibold">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-[var(--admin-line)] px-3" /></label>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <label className="text-sm font-semibold">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-lg border bg-white px-3"><option value="">Select {label.toLowerCase()}</option>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function TaxonomySelect({ label, kind, value, setValue, taxonomy }: { label: string; kind: string; value: string; setValue: (value: string) => void; taxonomy: AdminTaxonomyTerm[] }) { return <SelectField label={label} value={value} onChange={setValue} options={taxonomy.filter((term) => term.kind === kind).map((term) => [term.slug, term.name])} />; }
function MultiSelect({ label, options, values, setValues }: { label: string; options: AdminTaxonomyTerm[]; values: string[]; setValues: (values: string[]) => void }) { return <label className="text-sm font-semibold">{label}<select multiple value={values} onChange={(event) => setValues(Array.from(event.target.selectedOptions, (option) => option.value))} className="mt-2 min-h-28 w-full rounded-lg border bg-white p-2">{options.map((term) => <option key={term._id} value={term.slug}>{term.name}</option>)}</select></label>; }
function DynamicField({ attribute, specsText, onChange }: { attribute: AdminAttribute; specsText: string; onChange: (value: string) => void }) { let value: JsonValue | undefined; try { value = getNested(JSON.parse(specsText) as JsonObject, attribute.path.replace(/^specs\./, "").split(".")); } catch { value = undefined; } const text = value === undefined || value === null ? "" : String(value); if (attribute.dataType === "BOOLEAN") return <label className="text-sm font-semibold">{attribute.label}<select value={text} onChange={(event) => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-lg border bg-white px-3"><option value="">Not set</option><option value="true">Yes</option><option value="false">No</option></select></label>; if (attribute.dataType === "ENUM") return <SelectField label={attribute.label} value={text} onChange={onChange} options={attribute.options.map((option) => [option, formatLabel(option)])} />; return <TextField label={`${attribute.label}${attribute.unit ? ` (${attribute.unit})` : ""}`} value={text} onChange={onChange} type={attribute.dataType === "NUMBER" ? "number" : "text"} />; }
function setNested(object: JsonObject, path: string[], value: JsonValue) { let cursor = object; path.forEach((part, index) => { if (index === path.length - 1) cursor[part] = value; else { const next = cursor[part]; if (!next || Array.isArray(next) || typeof next !== "object") cursor[part] = {}; cursor = cursor[part] as JsonObject; } }); }
function getNested(object: JsonObject, path: string[]) { let cursor: JsonValue | undefined = object; for (const part of path) { if (!cursor || Array.isArray(cursor) || typeof cursor !== "object") return undefined; cursor = (cursor as JsonObject)[part]; } return cursor; }
function splitList(value: string) { return value.split(/\r?\n|,/).map((item) => item.trim()).filter(Boolean); }
function formatLabel(value: string) { return value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()); }
