"use client";

import { FormEvent, useState } from "react";
import { FiArchive, FiCheck, FiDollarSign, FiEdit2, FiLoader, FiStar, FiTag, FiX, FiXCircle } from "react-icons/fi";
import type { AdminListing, AdminListingPayload, JsonObject, JsonValue, ListingType } from "@autosecure/api";
import { adminApi, getAdminErrorMessage } from "@/lib/admin-api";
import { notifyError, notifySuccess } from "@/lib/admin-notifications";

export function ListingWorkspace({ mode, listing, accessToken, onClose, onEdit, onSaved, onApprove, onReject, onVerify, onArchive }: { mode: "view" | "edit" | "create"; listing: AdminListing | null; accessToken: string | null; onClose: () => void; onEdit: () => void; onSaved: (listing: AdminListing) => Promise<void>; onApprove: () => void; onReject: () => void; onVerify: () => void; onArchive: () => void }) {
  const [pricingOpen, setPricingOpen] = useState(false);
  const [hotDealOpen, setHotDealOpen] = useState(false);
  const [merchandisingBusy, setMerchandisingBusy] = useState(false);
  async function toggleFeatured() { if (!accessToken || !listing) return; setMerchandisingBusy(true); try { const response = await adminApi.updateListingFeatured(accessToken, listing._id, { isFeatured: !listing.isFeatured }); notifySuccess(listing.isFeatured ? "Listing removed from featured placement." : "Listing added to featured placement."); await onSaved(response.data); } catch (requestError) { notifyError(getAdminErrorMessage(requestError)); } finally { setMerchandisingBusy(false); } }
  return <><div className="fixed inset-0 z-50"><button type="button" aria-label="Close listing workspace" className="absolute inset-0 bg-slate-950/55" onClick={onClose} /><aside role="dialog" aria-modal="true" aria-labelledby="listing-workspace-title" className="absolute inset-y-0 right-0 w-full max-w-4xl overflow-y-auto bg-white shadow-2xl">
    <div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-5"><div><h2 id="listing-workspace-title" className="font-display text-xl font-bold">{mode === "create" ? "Add AutoSecure listing" : mode === "edit" ? "Edit listing" : listing?.title}</h2>{listing ? <p className="mt-1 text-xs text-[var(--admin-muted)]">{format(listing.type)} · {format(listing.status)}</p> : null}</div><button type="button" onClick={onClose} aria-label="Close" className="rounded-lg p-2 hover:bg-slate-100"><FiX /></button></div>
    {mode !== "view" ? <ListingForm item={mode === "edit" ? listing : null} accessToken={accessToken} onCancel={mode === "create" ? onClose : () => void onSaved(listing!)} onSaved={onSaved} /> : listing ? <div className="space-y-7 p-6">
      <div className="flex flex-wrap gap-2"><Action icon={FiEdit2} label="Edit" onClick={onEdit} disabled={listing.status === "ARCHIVED"} /><Action icon={FiDollarSign} label="Pricing" onClick={() => setPricingOpen(true)} disabled={listing.status === "ARCHIVED"} /><Action icon={FiTag} label="Hot Deal" onClick={() => setHotDealOpen(true)} disabled={listing.status === "ARCHIVED"} /><Action icon={FiStar} label={listing.isFeatured ? "Unfeature" : "Feature"} onClick={() => void toggleFeatured()} disabled={listing.status === "ARCHIVED" || merchandisingBusy} /><Action icon={FiCheck} label="Verify sections" onClick={onVerify} disabled={!listing.unverifiedSections?.length} /><Action icon={FiCheck} label="Approve" onClick={onApprove} disabled={listing.status === "APPROVED" || listing.status === "ARCHIVED" || Boolean(listing.unverifiedSections?.length)} /><Action icon={FiXCircle} label="Reject" onClick={onReject} disabled={listing.status === "REJECTED" || listing.status === "ARCHIVED"} danger /><Action icon={FiArchive} label="Archive" onClick={onArchive} disabled={listing.status === "ARCHIVED"} /></div>
      {listing.unverifiedSections?.length ? <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">Approval is blocked until these sections are verified: {listing.unverifiedSections.join(", ")}.</div> : null}
      <Section title="Customer-facing content"><dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Datum label="Title" value={listing.title} /><Datum label="Type" value={format(listing.type)} /><Datum label="Status" value={format(listing.status)} /><Datum label="Brand" value={listing.brand} /><Datum label="Model" value={listing.model} /><Datum label="Year" value={listing.year?.toString()} /><Datum label="Condition" value={listing.condition} /><Datum label="Transmission" value={listing.transmission} /><Datum label="Fuel type" value={listing.fuelType} /><Datum label="Part name" value={listing.partName} /><Datum label="Part category" value={listing.partCategory} /><Datum label="In stock" value={listing.inStock === undefined ? undefined : listing.inStock ? "Yes" : "No"} /></dl><p className="mt-5 whitespace-pre-wrap text-sm leading-6 text-[var(--admin-muted)]">{listing.description || "No description."}</p></Section>
      <Section title="Protected supplier and internal pricing"><div className="rounded-lg border border-red-100 bg-red-50 px-4 py-3 text-xs text-red-800">This information is for authenticated administrators and must not be copied into public customer payloads.</div><dl className="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Datum label="Owner" value={listing.isHouseListing ? "AutoSecure" : listing.supplier?.companyName ?? "Supplier"} /><Datum label="Supplier email" value={listing.supplier?.email} /><Datum label="Supplier phone" value={listing.supplier?.phone ?? undefined} /><Datum label="Retail price" value={money(listing.pricing?.retail, listing.pricing?.currency)} /><Datum label="Promotional price" value={money(listing.pricing?.promotional, listing.pricing?.currency)} /><Datum label="Fleet price" value={money(listing.pricing?.fleet, listing.pricing?.currency)} /></dl><div className="mt-5 border-t pt-4"><p className="text-xs font-bold text-[var(--admin-muted)]">Customer-facing price range</p><p className="mt-1 text-sm font-semibold">{rangeText(listing)}</p></div></Section>
      <Section title="Merchandising state"><dl className="grid gap-5 sm:grid-cols-3"><Datum label="Featured placement" value={listing.isFeatured ? "Featured" : "Not featured"} /><Datum label="Hot Deal" value={listing.hotDeal?.isActive ? "Active" : "Inactive"} /><Datum label="Hot Deal label" value={listing.hotDeal?.label} /></dl></Section>
      <Section title="Verification and provenance"><JsonView value={listing.provenance} /></Section>
      <details className="border-t pt-4"><summary className="cursor-pointer text-sm font-bold">Complete internal record</summary><JsonView value={listing as unknown as JsonObject} /></details>
    </div> : null}
  </aside></div>{listing && pricingOpen ? <PricingDialog listing={listing} accessToken={accessToken} onClose={() => setPricingOpen(false)} onSaved={async (updated) => { setPricingOpen(false); await onSaved(updated); }} /> : null}{listing && hotDealOpen ? <HotDealDialog listing={listing} accessToken={accessToken} onClose={() => setHotDealOpen(false)} onSaved={async (updated) => { setHotDealOpen(false); await onSaved(updated); }} /> : null}</>;
}

function ListingForm({ item, accessToken, onCancel, onSaved }: { item: AdminListing | null; accessToken: string | null; onCancel: () => void; onSaved: (listing: AdminListing) => Promise<void> }) {
  const [type, setType] = useState<ListingType>(item?.type ?? "BRAND_NEW_CAR");
  const [title, setTitle] = useState(item?.title ?? ""); const [description, setDescription] = useState(item?.description ?? ""); const [supplierId, setSupplierId] = useState("");
  const [brand, setBrand] = useState(item?.brand ?? ""); const [model, setModel] = useState(item?.model ?? ""); const [year, setYear] = useState(item?.year ? String(item.year) : ""); const [condition, setCondition] = useState(item?.condition ?? (type === "USED_CAR" ? "USED" : "NEW")); const [transmission, setTransmission] = useState(item?.transmission ?? "AUTOMATIC"); const [fuelType, setFuelType] = useState(item?.fuelType ?? "PETROL");
  const [partName, setPartName] = useState(item?.partName ?? ""); const [partCategory, setPartCategory] = useState(item?.partCategory ?? ""); const [retail, setRetail] = useState(item?.pricing?.retail === undefined ? "" : String(item.pricing.retail)); const [currency, setCurrency] = useState(item?.pricing?.currency ?? "NGN"); const [extra, setExtra] = useState("{}"); const [fieldError, setFieldError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setFieldError(""); if (!title.trim()) return setFieldError("Enter a listing title."); if (type === "PART" && !partName.trim()) return setFieldError("Enter the part name."); if (type !== "PART" && (!brand.trim() || !model.trim() || !year)) return setFieldError("Vehicle brand, model, and year are required."); let extras: JsonObject; try { extras = JSON.parse(extra) as JsonObject; if (!extras || Array.isArray(extras)) throw new Error(); } catch { return setFieldError("Additional fields must be a valid JSON object."); } if (!accessToken) return; const payload = { ...extras, type, title: title.trim(), description: description.trim() || undefined, status: item ? undefined : "DRAFT", supplierId: !item && supplierId.trim() ? supplierId.trim() : undefined, pricing: retail ? { retail: Number(retail), currency } : item?.pricing, brand: type === "PART" ? brand.trim() || undefined : brand.trim(), model: type === "PART" ? undefined : model.trim(), year: type === "PART" ? undefined : Number(year), condition, transmission: type === "PART" ? undefined : transmission, fuelType: type === "PART" ? undefined : fuelType, partName: type === "PART" ? partName.trim() : undefined, partCategory: type === "PART" ? partCategory.trim() || undefined : undefined, inStock: true } as AdminListingPayload; setSaving(true); try { const response = item ? await adminApi.updateListing(accessToken, item._id, payload) : await adminApi.createListing(accessToken, payload); notifySuccess(item ? "Listing updated." : "AutoSecure listing created as a draft."); await onSaved(response.data.listing); } catch (requestError) { notifyError(getAdminErrorMessage(requestError)); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="space-y-7 p-6"><Section title="Listing identity"><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Listing type" value={type} disabled={Boolean(item)} setValue={(value) => setType(value as ListingType)} options={[["BRAND_NEW_CAR", "Brand-new car"], ["USED_CAR", "Used car"], ["PART", "Part"]]} /><TextField label="Title" value={title} setValue={setTitle} /></div><label className="mt-4 block text-sm font-semibold">Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} className="mt-2 min-h-28 w-full rounded-lg border p-3" /></label>{!item ? <TextField label="Supplier ID (optional; blank uses AutoSecure)" value={supplierId} setValue={setSupplierId} /> : null}</Section>
    {type === "PART" ? <Section title="Part details"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Part name" value={partName} setValue={setPartName} /><TextField label="Part category" value={partCategory} setValue={setPartCategory} /><TextField label="Brand (optional)" value={brand} setValue={setBrand} /></div></Section> : <Section title="Vehicle details"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><TextField label="Brand" value={brand} setValue={setBrand} /><TextField label="Model" value={model} setValue={setModel} /><TextField label="Year" value={year} setValue={setYear} type="number" /><SelectField label="Condition" value={condition} setValue={setCondition} options={[["NEW", "New"], ["USED", "Used"]]} /><SelectField label="Transmission" value={transmission} setValue={setTransmission} options={[["AUTOMATIC", "Automatic"], ["MANUAL", "Manual"]]} /><SelectField label="Fuel type" value={fuelType} setValue={setFuelType} options={[["PETROL", "Petrol"], ["DIESEL", "Diesel"], ["HYBRID", "Hybrid"], ["ELECTRIC", "Electric"]]} /></div></Section>}
    <Section title="Initial internal price"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Retail price" value={retail} setValue={setRetail} type="number" /><TextField label="Currency" value={currency} setValue={setCurrency} /></div><p className="mt-2 text-xs text-[var(--admin-muted)]">Advanced internal and public range controls are handled in the next pricing step.</p></Section>
    <Section title="Additional API fields"><label className="block text-sm font-semibold">JSON object<textarea value={extra} onChange={(event) => setExtra(event.target.value)} className="mt-2 min-h-36 w-full rounded-lg border p-3 font-mono text-sm" /></label></Section>
    {fieldError ? <p role="alert" className="text-sm text-red-700">{fieldError}</p> : null}<div className="sticky bottom-0 flex justify-end gap-3 border-t bg-white py-4"><button type="button" onClick={onCancel} className="px-4 py-2 text-sm font-bold">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-[var(--admin-navy)] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? <FiLoader className="animate-spin" /> : null}{item ? "Save changes" : "Create draft"}</button></div></form>;
}

function PricingDialog({ listing, accessToken, onClose, onSaved }: { listing: AdminListing; accessToken: string | null; onClose: () => void; onSaved: (listing: AdminListing) => Promise<void> }) {
  const currentRange = listing.pricing?.priceRange ?? listing.priceRange;
  const [retail, setRetail] = useState(listing.pricing?.retail === undefined ? "" : String(listing.pricing.retail));
  const [currency, setCurrency] = useState(listing.pricing?.currency ?? currentRange?.currency ?? "NGN");
  const [rangeMode, setRangeMode] = useState<"automatic" | "manual">(currentRange?.isManual === false || !currentRange ? "automatic" : "manual");
  const [minimum, setMinimum] = useState(currentRange?.min === undefined ? "" : String(currentRange.min));
  const [maximum, setMaximum] = useState(currentRange?.max === undefined ? "" : String(currentRange.max));
  const [internal, setInternal] = useState(JSON.stringify(listing.pricing?.internal ?? {}, null, 2));
  const [fieldError, setFieldError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setFieldError(""); const retailValue = Number(retail); if (!retail || !Number.isFinite(retailValue) || retailValue < 0) return setFieldError("Enter a valid non-negative retail price."); let parsedInternal: JsonObject; try { parsedInternal = JSON.parse(internal) as JsonObject; if (!parsedInternal || Array.isArray(parsedInternal)) throw new Error(); } catch { return setFieldError("Internal pricing must be a valid JSON object."); } let priceRange: { min: number; max: number; currency: string } | null = null; if (rangeMode === "manual") { const min = Number(minimum); const max = Number(maximum); if (!minimum || !maximum || !Number.isFinite(min) || !Number.isFinite(max)) return setFieldError("Enter both customer-facing range values."); if (min > max) return setFieldError("The public minimum cannot exceed the public maximum."); priceRange = { min, max, currency }; } if (!accessToken) return; setSaving(true); try { const response = await adminApi.updateListingPricing(accessToken, listing._id, { retail: retailValue, currency, priceRange, internal: parsedInternal }); notifySuccess("Listing pricing updated."); await onSaved(response.data.listing); } catch (requestError) { notifyError(getAdminErrorMessage(requestError)); } finally { setSaving(false); } }
  return <Modal title="Edit listing pricing" onClose={onClose}><form onSubmit={submit} className="space-y-5"><div className="rounded-lg border border-red-100 bg-red-50 px-4 py-3 text-xs text-red-800">Retail and internal values are administrator-only. Only the separate range below is customer-facing.</div><div className="grid gap-4 sm:grid-cols-2"><TextField label="Exact retail price" value={retail} setValue={setRetail} type="number" /><TextField label="Currency" value={currency} setValue={setCurrency} /></div><fieldset className="border-t pt-4"><legend className="text-sm font-bold">Customer-facing range</legend><div className="mt-3 flex gap-5"><label className="flex gap-2 text-sm"><input type="radio" checked={rangeMode === "automatic"} onChange={() => setRangeMode("automatic")} /> Automatically derived</label><label className="flex gap-2 text-sm"><input type="radio" checked={rangeMode === "manual"} onChange={() => setRangeMode("manual")} /> Manual range</label></div>{rangeMode === "manual" ? <div className="mt-3 grid gap-4 sm:grid-cols-2"><TextField label="Public minimum" value={minimum} setValue={setMinimum} type="number" /><TextField label="Public maximum" value={maximum} setValue={setMaximum} type="number" /></div> : <p className="mt-3 text-xs text-[var(--admin-muted)]">The backend will derive the public range without exposing the exact retail price.</p>}</fieldset><label className="block border-t pt-4 text-sm font-semibold">Other internal cost fields (JSON)<textarea value={internal} onChange={(event) => setInternal(event.target.value)} className="mt-2 min-h-28 w-full rounded-lg border p-3 font-mono text-sm" /></label>{fieldError ? <p role="alert" className="text-sm text-red-700">{fieldError}</p> : null}<Buttons saving={saving} label="Save pricing" onCancel={onClose} /></form></Modal>;
}

function HotDealDialog({ listing, accessToken, onClose, onSaved }: { listing: AdminListing; accessToken: string | null; onClose: () => void; onSaved: (listing: AdminListing) => Promise<void> }) {
  const [active, setActive] = useState(listing.hotDeal?.isActive ?? false); const [label, setLabel] = useState(listing.hotDeal?.label ?? ""); const [startsAt, setStartsAt] = useState(toLocalDate(listing.hotDeal?.startsAt)); const [endsAt, setEndsAt] = useState(toLocalDate(listing.hotDeal?.endsAt)); const [fieldError, setFieldError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setFieldError(""); if (active && !label.trim()) return setFieldError("Enter a short Hot Deal label."); if (startsAt && endsAt && new Date(startsAt) >= new Date(endsAt)) return setFieldError("The end date must be later than the start date."); if (!accessToken) return; setSaving(true); try { const response = await adminApi.updateListingHotDeal(accessToken, listing._id, { isActive: active, label: label.trim() || undefined, startsAt: startsAt ? new Date(startsAt).toISOString() : undefined, endsAt: endsAt ? new Date(endsAt).toISOString() : undefined }); notifySuccess(active ? (response.data.isLive ? "Hot Deal activated and currently live." : "Hot Deal schedule saved.") : "Hot Deal disabled."); await onSaved(response.data.listing); } catch (requestError) { notifyError(getAdminErrorMessage(requestError)); } finally { setSaving(false); } }
  return <Modal title="Hot Deal settings" onClose={onClose}><form onSubmit={submit} className="space-y-5"><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} /> Promote this listing as a Hot Deal</label><TextField label="Customer-facing label" value={label} setValue={setLabel} /><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Starts at<input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} className="mt-2 h-11 w-full rounded-lg border px-3" /></label><label className="text-sm font-semibold">Ends at<input type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} className="mt-2 h-11 w-full rounded-lg border px-3" /></label></div>{fieldError ? <p role="alert" className="text-sm text-red-700">{fieldError}</p> : null}<Buttons saving={saving} label="Save Hot Deal" onCancel={onClose} /></form></Modal>;
}

export function RejectDialog({ listing, accessToken, onClose, onSaved }: { listing: AdminListing; accessToken: string | null; onClose: () => void; onSaved: (listing: AdminListing) => Promise<void> }) { const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); if (reason.trim().length < 10) return setError("Give the supplier a clear reason of at least 10 characters."); if (!accessToken) return; setSaving(true); try { const response = await adminApi.rejectListing(accessToken, listing._id, { reason: reason.trim() }); notifySuccess("Listing rejected with supplier feedback."); await onSaved(response.data); } catch (requestError) { notifyError(getAdminErrorMessage(requestError)); } finally { setSaving(false); } } return <Modal title="Reject listing" onClose={onClose}><form onSubmit={submit}><label className="text-sm font-semibold">Reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} className="mt-2 min-h-32 w-full rounded-lg border p-3" /></label>{error ? <p className="mt-2 text-sm text-red-700">{error}</p> : null}<Buttons saving={saving} label="Reject listing" onCancel={onClose} /></form></Modal>; }
export function VerifyListingDialog({ listing, accessToken, onClose, onSaved }: { listing: AdminListing; accessToken: string | null; onClose: () => void; onSaved: (listing: AdminListing) => Promise<void> }) { const pending = listing.unverifiedSections ?? []; const [sections, setSections] = useState(pending); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); if (!accessToken || !sections.length) return; setSaving(true); try { const response = await adminApi.verifyListingSections(accessToken, listing._id, { sections: sections.length === pending.length ? "all" : sections, note: note.trim() || undefined }); notifySuccess("Listing sections verified."); await onSaved(response.data.listing); } catch (requestError) { notifyError(getAdminErrorMessage(requestError)); } finally { setSaving(false); } } return <Modal title="Verify listing sections" onClose={onClose}><form onSubmit={submit} className="space-y-4">{pending.map((section) => <label key={section} className="flex gap-3 text-sm"><input type="checkbox" checked={sections.includes(section)} onChange={() => setSections((current) => current.includes(section) ? current.filter((value) => value !== section) : [...current, section])} />{format(section)}</label>)}<label className="block text-sm font-semibold">Note<textarea value={note} onChange={(event) => setNote(event.target.value)} className="mt-2 min-h-24 w-full rounded-lg border p-3" /></label><Buttons saving={saving} label="Verify selected" onCancel={onClose} disabled={!sections.length} /></form></Modal>; }

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center p-5"><button type="button" aria-label="Close" className="absolute inset-0 bg-slate-950/55" onClick={onClose} /><div role="dialog" className="relative w-full max-w-lg rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="font-display text-xl font-bold">{title}</h2><button onClick={onClose}><FiX /></button></div>{children}</div></div>; }
function Buttons({ saving, label, onCancel, disabled = false }: { saving: boolean; label: string; onCancel: () => void; disabled?: boolean }) { return <div className="mt-5 flex justify-end gap-3 border-t pt-4"><button type="button" onClick={onCancel} className="px-4 py-2 text-sm font-bold">Cancel</button><button disabled={saving || disabled} className="inline-flex items-center gap-2 rounded-lg bg-[var(--admin-navy)] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? <FiLoader className="animate-spin" /> : null}{label}</button></div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border-b pb-6"><h3 className="mb-4 font-display text-lg font-bold">{title}</h3>{children}</section>; }
function Datum({ label, value }: { label: string; value?: string }) { return <div><dt className="text-xs font-bold text-[var(--admin-muted)]">{label}</dt><dd className="mt-1 text-sm font-semibold">{value || "Not set"}</dd></div>; }
function Action({ icon: Icon, label, onClick, disabled = false, danger = false }: { icon: typeof FiEdit2; label: string; onClick: () => void; disabled?: boolean; danger?: boolean }) { return <button type="button" onClick={onClick} disabled={disabled} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-40 ${danger ? "border-red-200 text-red-700" : ""}`}><Icon />{label}</button>; }
function TextField({ label, value, setValue, type = "text" }: { label: string; value: string; setValue: (value: string) => void; type?: "text" | "number" }) { return <label className="mt-4 block text-sm font-semibold">{label}<input type={type} value={value} onChange={(event) => setValue(event.target.value)} className="mt-2 h-11 w-full rounded-lg border px-3" /></label>; }
function SelectField({ label, value, setValue, options, disabled = false }: { label: string; value: string; setValue: (value: string) => void; options: string[][]; disabled?: boolean }) { return <label className="text-sm font-semibold">{label}<select value={value} disabled={disabled} onChange={(event) => setValue(event.target.value)} className="mt-2 h-11 w-full rounded-lg border bg-white px-3 disabled:bg-slate-100">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function JsonView({ value }: { value?: JsonValue | JsonObject }) { return <pre className="overflow-x-auto rounded-lg bg-slate-50 p-4 text-xs leading-5">{JSON.stringify(value ?? {}, null, 2)}</pre>; }
function money(value?: number, currency = "NGN") { return value === undefined ? undefined : new Intl.NumberFormat("en-NG", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); }
function rangeText(listing: AdminListing) { const range = listing.pricing?.priceRange ?? listing.priceRange; if (!range || range.min === undefined || range.max === undefined) return "Automatically derived"; return `${money(range.min, range.currency)} – ${money(range.max, range.currency)}${range.isManual === false ? " (automatic)" : ""}`; }
function toLocalDate(value?: string) { if (!value) return ""; const date = new Date(value); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
function format(value: string) { return value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()); }
