"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { FiChevronDown, FiChevronUp, FiEdit2, FiLoader, FiPlus, FiTrash2, FiX } from "react-icons/fi";
import { ApiError, type AdminOrderStage } from "@autosecure/api";
import { AdminConfirmationDialog, AdminEmptyState, AdminErrorState, AdminLoadingState, AdminPageHeader } from "@/components/ui/AdminPrimitives";
import { adminApi, getAdminErrorMessage } from "@/lib/admin-api";
import { notifyError, notifySuccess, notifyWarning } from "@/lib/admin-notifications";
import { useAdminAuthStore } from "@/stores/auth-store";

export function OrderStagesRoute() { const token = useAdminAuthStore((s) => s.accessToken); const [stages,setStages]=useState<AdminOrderStage[]>([]); const [editing,setEditing]=useState<AdminOrderStage|"new"|null>(null); const [deleting,setDeleting]=useState<AdminOrderStage|null>(null); const [conflict,setConflict]=useState<AdminOrderStage|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  const load=useCallback(async()=>{if(!token)return;setLoading(true);setError("");try{const r=await adminApi.getOrderStages(token);setStages(r.data);}catch(e){setError(getAdminErrorMessage(e));}finally{setLoading(false);}},[token]); useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t);},[load]);
  async function reorder(index:number,direction:-1|1){if(!token)return;const target=index+direction;if(target<0||target>=stages.length)return;const next=[...stages];[next[index],next[target]]=[next[target],next[index]];setBusy("reorder");try{await adminApi.reorderOrderStages(token,next.map((s,i)=>({id:s._id,order:(i+1)*10})));notifySuccess("Order stages reordered.");await load();}catch(e){notifyError(getAdminErrorMessage(e));}finally{setBusy("");}}
  async function remove(){if(!token||!deleting)return;const stage=deleting;setBusy(stage._id);try{await adminApi.deleteOrderStage(token,stage._id);setDeleting(null);notifySuccess("Order stage deleted.");await load();}catch(e){setDeleting(null);if(e instanceof ApiError&&(e.status===400||e.status===409)){setConflict(stage);notifyWarning("This stage is protected or referenced. Deactivate it instead.");}else notifyError(getAdminErrorMessage(e));}finally{setBusy("");}}
  async function deactivate(){if(!token||!conflict)return;setBusy(conflict._id);try{await adminApi.updateOrderStage(token,conflict._id,{isActive:false});setConflict(null);notifySuccess("Order stage deactivated.");await load();}catch(e){notifyError(getAdminErrorMessage(e));}finally{setBusy("");}}
  return <><AdminPageHeader title="Order stages" description="Configure the ordered workflow used for customer order timelines." actions={<button onClick={()=>setEditing("new")} className="inline-flex items-center gap-2 rounded-lg bg-[var(--admin-navy)] px-4 py-2 text-sm font-bold text-white"><FiPlus/> Add stage</button>}/>{error?<AdminErrorState message={error} onRetry={()=>void load()}/>:loading?<AdminLoadingState/>:stages.length?<section className="overflow-x-auto rounded-2xl border bg-white"><div className="min-w-[760px]">{stages.map((stage,index)=><div key={stage._id} className="grid grid-cols-[0.8fr_1fr_1.5fr_0.6fr_1.2fr] items-center gap-4 border-b px-5 py-4"><code className="text-xs">{stage.key}</code><span className="text-sm font-bold">{stage.label}</span><span className="text-sm text-[var(--admin-muted)]">{stage.description||"No description"}</span><span className="text-xs">{stage.isActive?"Active":"Inactive"}{stage.isTerminal?" / Terminal":""}</span><div className="flex justify-end gap-2"><button disabled={index===0||busy==="reorder"} onClick={()=>void reorder(index,-1)} aria-label={`Move ${stage.label} up`} className="rounded border p-2 disabled:opacity-30"><FiChevronUp/></button><button disabled={index===stages.length-1||busy==="reorder"} onClick={()=>void reorder(index,1)} aria-label={`Move ${stage.label} down`} className="rounded border p-2 disabled:opacity-30"><FiChevronDown/></button><button onClick={()=>setEditing(stage)} className="rounded border p-2" aria-label={`Edit ${stage.label}`}><FiEdit2/></button><button onClick={()=>setDeleting(stage)} className="rounded p-2 text-red-600" aria-label={`Delete ${stage.label}`}><FiTrash2/></button></div></div>)}</div></section>:<AdminEmptyState title="No order stages" description="Add the first workflow stage."/>}{editing?<StageEditor item={editing==="new"?null:editing} token={token} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load();}}/>:null}{deleting?<AdminConfirmationDialog title="Delete order stage?" description={`Delete ${deleting.label}? Referenced or immutable stages must be deactivated instead.`} confirmLabel="Delete" tone="danger" isLoading={busy===deleting._id} onCancel={()=>setDeleting(null)} onConfirm={()=>void remove()}/>:null}{conflict?<AdminConfirmationDialog title="Stage cannot be deleted" description={`${conflict.label} is protected or used by orders. Deactivate it while preserving existing histories.`} confirmLabel="Deactivate" isLoading={busy===conflict._id} onCancel={()=>setConflict(null)} onConfirm={()=>void deactivate()}/>:null}</>;
}
function StageEditor({item,token,onClose,onSaved}:{item:AdminOrderStage|null;token:string|null;onClose:()=>void;onSaved:()=>Promise<void>}){const[key,setKey]=useState(item?.key??"");const[label,setLabel]=useState(item?.label??"");const[description,setDescription]=useState(item?.description??"");const[order,setOrder]=useState(String(item?.order??0));const[terminal,setTerminal]=useState(item?.isTerminal??false);const[active,setActive]=useState(item?.isActive??true);const[error,setError]=useState("");const[saving,setSaving]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(!key.trim()||!label.trim())return setError("Key and label are required.");if(!token)return;setSaving(true);try{const payload={key:key.trim().toUpperCase().replaceAll(" ","_"),label:label.trim(),description:description.trim()||undefined,order:Number(order),isTerminal:terminal,isActive:active};if(item){const{key:_key,...updates}=payload;void _key;await adminApi.updateOrderStage(token,item._id,updates);}else await adminApi.createOrderStage(token,payload);notifySuccess(item?"Order stage updated.":"Order stage created.");await onSaved();}catch(err){notifyError(getAdminErrorMessage(err));}finally{setSaving(false);}}return <div className="fixed inset-0 z-50"><button className="absolute inset-0 bg-slate-950/55" onClick={onClose}/><aside className="absolute inset-y-0 right-0 w-full max-w-xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">{item?"Edit stage":"Add stage"}</h2><button onClick={onClose}><FiX/></button></div><form onSubmit={submit} className="mt-6 space-y-4"><Field label="Immutable key" value={key} setValue={setKey} disabled={Boolean(item)}/><Field label="Label" value={label} setValue={setLabel}/><Field label="Description" value={description} setValue={setDescription}/><Field label="Order" value={order} setValue={setOrder} type="number"/><label className="flex gap-2"><input type="checkbox" checked={terminal} onChange={e=>setTerminal(e.target.checked)}/>Terminal stage</label><label className="flex gap-2"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Active</label>{error?<p className="text-red-700">{error}</p>:null}<button disabled={saving} className="inline-flex items-center gap-2 rounded bg-[var(--admin-navy)] px-4 py-2 font-bold text-white">{saving?<FiLoader className="animate-spin"/>:null}Save stage</button></form></aside></div>}
function Field({label,value,setValue,disabled=false,type="text"}:{label:string;value:string;setValue:(v:string)=>void;disabled?:boolean;type?:"text"|"number"}){return <label className="block text-sm font-semibold">{label}<input type={type} value={value} disabled={disabled} onChange={e=>setValue(e.target.value)} className="mt-2 h-11 w-full rounded-lg border px-3 disabled:bg-slate-100"/></label>}
